server:
  port: 8888
spring:  datasource:    url: jdbc:h2:mem:testdb 
    driver-class-name: org.h2.Driver
    username: sa
    password:   h2:    console:      enabled: false      path: /h2  jpa:    hibernate:      ddl-auto: update

check-user-scopes: true
